import { Member } from './types';

export const MEMBERS: Member[] = [
  { id: '1', name: 'Ajay Gumbar', company: 'Taxonym Advisors LLP', category: 'Tax Law', color: '#EF4444' },
  { id: '2', name: 'Alok Ranjan', company: 'Ioteraction Technologies Services Pvt Ltd', category: 'Advertising', color: '#F97316' },
  { id: '3', name: 'Anjali Mathur', company: 'Capers Corporate Wellness Pvt Ltd', category: 'Corp Wellness', color: '#F59E0B' },
  { id: '4', name: 'Arjit Benjamin', company: 'Prosoll Law', category: 'IP Law', color: '#10B981' },
  { id: '5', name: 'Chandan Monga', company: 'ALL GLASS & ALUMINIUM SOLUTION', category: 'Glass', color: '#06B6D4' },
  { id: '6', name: 'Charru Kulthia', company: 'Consciouspaces IN', category: 'Interiors (Comm)', color: '#3B82F6' },
  { id: '7', name: 'Dharmesh Sharma', company: 'PMP Insurance Broking LLP', category: 'Gen Insurance', color: '#6366F1' },
  { id: '8', name: 'Divyanshu Verma', company: 'Konverzions', category: 'Web Dev', color: '#8B5CF6' },
  { id: '9', name: 'Dr. Rahul Raj', company: 'The Dental Villa', category: 'Dentist', color: '#EC4899' },
  { id: '10', name: 'Garv Bakshi', company: 'Graf Interiors', category: 'Office Furniture', color: '#F43F5E' },
  { id: '11', name: 'Gaurav Sarna', company: 'Sitarra & Co', category: 'Wedding Planner', color: '#84CC16' },
  { id: '12', name: 'Gautam Jain', company: 'GRK ASSOCIATES', category: 'Life Insurance', color: '#14B8A6' },
  { id: '13', name: 'Harsh Gupta', company: 'Hamsa Homes and Lifestyle', category: 'Home Furnishings', color: '#0EA5E9' },
  { id: '14', name: 'Harsh Vardhan Sharma', company: 'BetterFinance.in', category: 'Finance', color: '#22C55E' },
  { id: '15', name: 'Ishan Gupta', company: 'Ishika Sanitary & Hardware Udyog', category: 'Bath Accessories', color: '#EAB308' },
  { id: '16', name: 'Jatin Choudhary', company: 'Swajat', category: 'Apparel', color: '#D946EF' },
  { id: '17', name: 'Kunj Kalra', company: 'SOLLUZ ENERGY PVT LTD', category: 'Solar', color: '#F472B6' },
  { id: '18', name: 'Manish Malhotra', company: 'PROP 24', category: 'Real Estate', color: '#FB923C' },
  { id: '19', name: 'Meenu Singh', company: 'Timeless Tales by Meenu', category: 'Furniture Mfg', color: '#A3E635' },
  { id: '20', name: 'Mitali Bansal', company: 'Genesis Pro Pac', category: 'Packaging', color: '#2DD4BF' },
  { id: '21', name: 'Naveen Gupta', company: 'TREV MOBILITY TECH PRIVATE LIMITED', category: 'Travel', color: '#38BDF8' },
  { id: '22', name: 'Pushp Wadera', company: 'Pushp International', category: 'Kitchen Const', color: '#818CF8' },
  { id: '23', name: 'Rajat Sharma', company: 'TRAVEL WORLD', category: 'Travel', color: '#C084FC' },
  { id: '24', name: 'Ria Kachhawaha', company: 'App Theka', category: 'App Dev', color: '#F471B5' },
  { id: '25', name: 'Robin Garg', company: 'PRJ Jeweller', category: 'Fine Jewelry', color: '#FB7185' },
  { id: '26', name: 'Samika Sharma', company: 'DS Dezigns', category: 'Interiors (Res)', color: '#4ADE80' },
  { id: '27', name: 'Saummay Sharma', company: 'Jai Shree Electricals', category: 'Electrical Eq', color: '#22D3EE' },
  { id: '28', name: 'Saurabh Malhotra', company: 'Lightpillar', category: 'Wealth Mgmt', color: '#60A5FA' },
  { id: '29', name: 'Saurabh Sibal', company: 'SGS Enterprises', category: 'Corporate Events', color: '#A78BFA' },
  { id: '30', name: 'Shubham Sethi', company: 'Optmum Digital Marketing', category: 'SEO', color: '#E879F9' },
  { id: '31', name: 'Sonal Mehta', company: 'Resurgent India Limited', category: 'Financial Advisor', color: '#FBBF24' },
  { id: '32', name: 'Sumit Nagpal', company: 'P&R Law Chambers', category: 'Civil Law', color: '#A855F7' },
  { id: '33', name: 'Supreet Singh', company: 'Strategic Strides', category: 'HR', color: '#EC4899' },
  { id: '34', name: 'Tamanna Gupta', company: 'Sarmaya Homes', category: 'Retail', color: '#F43F5E' },
  { id: '35', name: 'Vinay Malik', company: 'Jay Dee Sales Corp', category: 'Construction', color: '#10B981' },
  { id: '36', name: 'Vipul Arora', company: 'Growtech Today', category: 'Landscape', color: '#3B82F6' },
  { id: '37', name: 'Yogendra Singh', company: 'ExcelDes Spaces', category: 'Architect', color: '#F59E0B' },
];